In [23]:
import pandas as pd
import random
import string
import numpy as np

# load data
original_df = pd.read_csv("Customers_data.csv")

# create an imaginary Salary so we also have some numeric column
original_df['Salary'] = np.random.randint(25000, 175000, size=len(original_df))

# due to some of the anonymization methods
# for being quite heavy and slow, we'll try these 
# on a smaller sample
original_df = original_df.iloc[0:1000]
original_df

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,62254
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,40032
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,56172
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,111365
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,90852
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,121489
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,61761
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,26406
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,93741
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),27364

<b>Experiment 1: Randomization</b>

In [24]:
# define function that operates on entire dataframe
def randomize_values(df):
    for column in df.columns:
        if df[column].dtype == 'O': # check if column has object dtype
            df[column] = [''.join(random.choices(string.ascii_letters + string.digits, k=10)) for _ in range(len(df))] # generate a list of random strings
    return df

# apply function to dataframe
df_rand = randomize_values(original_df.copy())


# all values but numeric are now randomized
df_rand

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,nxJVFwO9jr,dWTuyXWqnG,dWl3CpdAhO,4azl2HhM8l,5jjkZ7rk8v,9Lv4BsgvlC,mTV5JPFpVA,im0PSJP5K8,XJI3lWMrJS,62254
1,pBrnqtOvG4,CSpL4GAa84,3YBrMoBV5j,W2S5UTeUM2,fF0m1DCeIf,q7ugS36B2m,0mpTc0EFOE,9LDXE69Ocw,upOzT3DTG3,40032
2,gclrcR4ZnS,KsHcFfGSpR,aKhKvvFexs,vRw1Rpc6RU,HZBgdRVGSM,6mDzr33VJz,6uNqMGBta2,ZOjyyFV8YA,asqjfQDk0j,56172
3,IgLIxVZ4mG,DiB0pUpEWE,Pn8n6kfu7d,aX8EftTZnN,hyhogs2wGY,bbureDOc4d,8GjAmy3xaj,t7PPKPiere,ARW61g8vJB,111365
4,wpH0SwWe1d,veGRoPWvZP,OHs9beRqAh,Jwxrcjjy8z,I3dnO8WNxh,dtiSws7xhm,qp6cIkmXte,40C7wdzXCp,BxRJw93yvu,90852
...,...,...,...,...,...,...,...,...,...,...
995,PHXHhvdzR0,KkOZL6ITxU,zAv6nZkV64,tjcw34nRjH,87xOkNR5P8,LcvlRZsEby,KVXluVqtdu,q9TvOKjqso,keJpgnrV8w,121489
996,mLUZI1Cu1C,5l6VX2OhAn,J38jwCLzbq,0V2Xvq9HG4,57ZutvDqy3,CabZzrzDrJ,X0OvzzUIVJ,uYv4pA1xt6,sDYiLfBIZD,61761
997,7vhnO1kjgv,upnufSmxNJ,aOBUN3Rpwg,ByZCQr5nCJ,F0eBNbWk9X,BCIDzomT3b,l9TBqCCaOZ,ZtyyUAml9x,V65RSEiha2,26406
998,ySdWIRU2PR,X1yrEgK8lt,4STJjex0m6,QI6KX1Mjz6,xsHAYkYRj4,9YSpH4isD4,BT0YvN0BtP,uH1rX73ZGV,XU0ViY2zjK,93741
999,SL987wKpks,Q1Wrz5NAJA,dnRa9HLoCh,W8Be6aZIhM,hBwbrXGAAF,ulS7Kh8LaP,QsYz4cjRSP,sKcBxXY8Do,22gKBVRlOg,27364

In [25]:
# test index to compare the real and randomized data row
selected_index = 567

In [26]:
df_rand.iloc[selected_index].to_frame()

                567
Name     HMMKZnujEH
Address  GFlTSSeqRt
Email    F2uf6j7z1M
Job      MdOEKwuyWF
Company  m2DlvBn4nS
Date     BijdCAdstr
Phone    u8FtPNXFbj
City     XCwBPKsaim
Country  dAqmt6FVsh
Salary        92592

In [27]:
# the original dataframe should be in a lookup table
# so it would be possible to trace back the original values as well
# the lookup table should be stored securely though
original_df.iloc[selected_index].to_frame()

                                                       567
Name                                           Brian Craig
Address  55300 Thomas Island Suite 866\nWest Johnny, MH...
Email                       michaelchristensen@example.com
Job                                    Associate Professor
Company                                      Vargas-Nguyen
Date                                            1959-04-15
Phone                                +1-962-665-3098x66494
City                                     West Vincenthaven
Country                                    Solomon Islands
Salary                                               92592

<b>Experiment 2: Aggregation (summary, simplify, group by data)</b>

In [28]:
# Anonymize the ages by grouping them into age ranges
bins = [0, 30_000, 50_000, 80_000, 120_000, 200_000]
labels = ['0-30K', '31-50K', '51-80K', '81-120K', '120K+']
df_rand['Salary'] = pd.cut(df_rand['Salary'], bins=bins, labels=labels)

In [29]:
df_rand

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,nxJVFwO9jr,dWTuyXWqnG,dWl3CpdAhO,4azl2HhM8l,5jjkZ7rk8v,9Lv4BsgvlC,mTV5JPFpVA,im0PSJP5K8,XJI3lWMrJS,51-80K
1,pBrnqtOvG4,CSpL4GAa84,3YBrMoBV5j,W2S5UTeUM2,fF0m1DCeIf,q7ugS36B2m,0mpTc0EFOE,9LDXE69Ocw,upOzT3DTG3,31-50K
2,gclrcR4ZnS,KsHcFfGSpR,aKhKvvFexs,vRw1Rpc6RU,HZBgdRVGSM,6mDzr33VJz,6uNqMGBta2,ZOjyyFV8YA,asqjfQDk0j,51-80K
3,IgLIxVZ4mG,DiB0pUpEWE,Pn8n6kfu7d,aX8EftTZnN,hyhogs2wGY,bbureDOc4d,8GjAmy3xaj,t7PPKPiere,ARW61g8vJB,81-120K
4,wpH0SwWe1d,veGRoPWvZP,OHs9beRqAh,Jwxrcjjy8z,I3dnO8WNxh,dtiSws7xhm,qp6cIkmXte,40C7wdzXCp,BxRJw93yvu,81-120K
...,...,...,...,...,...,...,...,...,...,...
995,PHXHhvdzR0,KkOZL6ITxU,zAv6nZkV64,tjcw34nRjH,87xOkNR5P8,LcvlRZsEby,KVXluVqtdu,q9TvOKjqso,keJpgnrV8w,120K+
996,mLUZI1Cu1C,5l6VX2OhAn,J38jwCLzbq,0V2Xvq9HG4,57ZutvDqy3,CabZzrzDrJ,X0OvzzUIVJ,uYv4pA1xt6,sDYiLfBIZD,51-80K
997,7vhnO1kjgv,upnufSmxNJ,aOBUN3Rpwg,ByZCQr5nCJ,F0eBNbWk9X,BCIDzomT3b,l9TBqCCaOZ,ZtyyUAml9x,V65RSEiha2,0-30K
998,ySdWIRU2PR,X1yrEgK8lt,4STJjex0m6,QI6KX1Mjz6,xsHAYkYRj4,9YSpH4isD4,BT0YvN0BtP,uH1rX73ZGV,XU0ViY2zjK,81-120K
999,SL987wKpks,Q1Wrz5NAJA,dnRa9HLoCh,W8Be6aZIhM,hBwbrXGAAF,ulS7Kh8LaP,QsYz4cjRSP,sKcBxXY8Do,22gKBVRlOg,0-30K

In [30]:
# as we can see, the exact salaries are no longer in the dataset
# a salary range is used instead
# this way, of course, we lose some information though 
# (can be suboptimal for a machine learning model)
original_df

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,62254
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,40032
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,56172
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,111365
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,90852
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,121489
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,61761
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,26406
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,93741
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),27364

<b>Experiment 3: Masking</b>

In [31]:
original_df.columns

Index(['Name', 'Address', 'Email', 'Job', 'Company', 'Date', 'Phone', 'City',
       'Country', 'Salary'],
      dtype='object')

In [32]:
# pip install anonymizedf
from anonymizedf.anonymizedf import anonymize

# prepare data for anonymization
an = anonymize(original_df.copy())

# add masked columns
# NOTE! with large complex datasets
# it can take a considerable time to generate these
fake_df = (
    an
    .fake_names("Name", chaining=True)
    .fake_whole_numbers("Salary", chaining=True)
    .fake_names("Address", chaining=True)
    .fake_names("Email", chaining=True)
    .fake_categories("City", chaining=True)
    .fake_categories("Company", chaining=True)
    .fake_categories("Country", chaining=True)
    .fake_categories("Job", chaining=True)
    .fake_dates("Date", chaining=True)
    .fake_names("Phone", chaining=True)
    .show_data_frame()
)

# subset only anonymized columns
# fake_df = fake_df[['Fake_Name', 'Fake_Salary', 'Fake_Age', 'Fake_City', 'Fake_HouseNumber', 'StreetName']]

fake_df.columns

Index(['Name', 'Address', 'Email', 'Job', 'Company', 'Date', 'Phone', 'City',
       'Country', 'Salary', 'Fake_Name', 'Fake_Salary', 'Fake_Address',
       'Fake_Email', 'Fake_City', 'Fake_Company', 'Fake_Country', 'Fake_Job',
       'Fake_Date', 'Fake_Phone'],
      dtype='object')

In [33]:
fake_df[['Fake_Name', 'Fake_Salary', 'Fake_Address',
       'Fake_Email', 'Fake_City', 'Fake_Company', 'Fake_Country', 'Fake_Job',
       'Fake_Date', 'Fake_Phone']]

,Fake_Name,Fake_Salary,Fake_Address,Fake_Email,Fake_City,Fake_Company,Fake_Country,Fake_Job,Fake_Date,Fake_Phone
0,Owen Brady,114354,Mr Martin Long,Deborah Hamilton,City 1,Company 1,Country 1,Job 1,1994-08-08,Michelle Harris-Hamilton
1,Mr Terence Hill,63314,Dr Charlie Smith,Deborah Richardson,City 2,Company 2,Country 2,Job 2,2024-04-10,Nicola Wilson-Smith
2,Patrick Smith,77546,Mr Mohammed Hughes,Irene Allen-Brown,City 3,Company 3,Country 3,Job 3,1973-03-08,Leanne Brown
3,Lynda Howard,72732,Mrs Amelia Greenwood,Ms Diane Williams,City 4,Company 4,Country 4,Job 4,2020-04-16,Mohamed Evans
4,Mr Justin White,145823,Clive Lane,Adrian Connor,City 5,Company 5,Country 5,Job 5,2015-06-07,Hazel Watson
...,...,...,...,...,...,...,...,...,...,...
995,Howard Nash-Woodward,97835,Cheryl Williams,Colin Glover,City 967,Company 976,Country 229,Job 111,1984-05-17,Mrs Katie Webster
996,Tom Wong,110718,Jonathan Lee,Luke Atkinson,City 968,Company 977,Country 65,Job 245,2008-09-27,Josephine Harris
997,Mr Nicholas Jones,128332,Robert Jarvis,Jacqueline Joyce,City 969,Company 978,Country 205,Job 211,1971-05-30,Alice Newman
998,Jenna Ball,122412,Douglas Grant,Leah Ellis,City 970,Company 979,Country 40,Job 322,2009-06-07,Dr Donald Green
999,Jenna Gray-Thomas,86180,Mr Danny Banks,Alan Hunt,City 971,Company 980,Country 189,Job 395,1995-06-19,Carly Baker

<b>Experiment 4: Perturbation</b>

In [34]:
def add_noise(df, column, std = None):
    if std == None:
        std = df[column].std()
    
    withNoise = df[column].add(np.random.normal(0, std, df.shape[0]))
    copy = df.copy()
    copy[column] = withNoise
    return copy


# adds a small noise to Salary so it's not exactly matching with real data
perturbation = add_noise(original_df, 'Salary', std=100)
perturbation

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,62229.938309
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,40018.497794
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,56179.363514
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,111362.219165
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,90969.423029
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,121368.225817
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,61788.347435
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,26320.690701
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,93810.719054
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),27376.992552

<b>Note: these experiments are probably just some of the options for data anonymization! However, a rule of thumb is, we can't assume a single anonymization method is enough for, let's say, GDPR-compliance.</b><br /><br /><b>The data has to be anonymized in all needed ways so that outsiders can't deduce individual people from the processed data.</b>